
export const SEARCH_CONTENT_SAGA = "SEARCH_CONTENT_SAGA";
export const SEARCH_CONTENT = "SEARCH_CONTENT";

export const SEARCH_TIMING_SAGA = "SEARCH_TIMING_SAGA";
export const SEARCH_TIMING = "SEARCH_TIMING";